Custom input
robinhood-agency/tg-bot-showcase-client pull request #9
Opened 2024-08-29 16:52 UTC by skranee

https://github.com/user-attachments/assets/af08d039-2ba9-437e-b677-06477029ea61

2024-08-29 18:04 UTC, Murz4 requested changes

2024-08-30 07:40 UTC, skranee commented on src/common/components/CustomInput/CustomInput.tsx
> +        id={label}
id is needed in order to relate the <label> tag to the input

2024-08-30 07:41 UTC, skranee commented on src/common/components/CustomInput/CustomInput.tsx
> +        value={value}
I've tried to make the interface for the component extend an <input> tag and be able to have basic input props, but somehow value was not there, while onChange() for example worked just fine, so I needed value to be in props

2024-08-30 07:44 UTC, skranee commented on src/common/components/CustomInput/CustomInput.tsx
> +        placeholder={label}
placeholder is now working as value, also placeholder value here is the same as ID and label - it's {label}, so you just need to pass only one props {label}, placeholder is invisible anyway because it's used to create a floating label animation only, instead of placeholder inside of input you see <label>

2024-08-30 07:45 UTC, skranee commented on src/common/components/CustomInput/CustomInput.tsx
> +      <label htmlFor={label} className={styles.inputContainer__label}>{ label }</label>
it's a React variant of 'for', it's used to relate the label to a component, if you look in the browser, this htmlFor is transformed into default js 'for' when it's mounted

2024-08-30 07:46 UTC, skranee commented on src/common/components/CustomInput/CustomInput.tsx
> +  value?: string
already told about value

2024-08-30 12:19 UTC, Murz4 approved these changes

2024-08-30 12:19 UTC, merged